Insights updates
rxrevu/workstation-setup pull request #11
Opened 2021-03-26 15:14 UTC by jtzero

I added this in two commits. We don;t use pycharm but intellij, as we use multiple facets of intellij (python, datagrip, etc), I don;t know if python.sh is the right place for it....

2021-03-26 15:19 UTC, kimdhendrick commented on scripts/opt-in/python.sh
> +echo "Installing IntelliJ"
you're installing IntelliJ in the python.sh script?

2021-03-26 15:27 UTC, pgoodwin requested changes

2021-03-26 15:27 UTC, pgoodwin commented on scripts/opt-in/python.sh
> +echo "Installing IntelliJ"
We install IntelliJ in the java-tools.sh script. Maybe it should be broken out into its own optional script. It's a multi-language tool so there are a lot of different reasons for installing it. Let's make sure to preserve the guards that are in place in the java-tools.sh script that prevent existing configuration from being inadvertently overwritten.

2021-03-26 19:37 UTC, pgoodwin requested changes

2021-03-26 19:37 UTC, pgoodwin commented on scripts/opt-in/python.sh
> -
Should there also be a separate pycharm.sh script?

In any case, please update the README.md to reflect these changes so that folks know exactly what command to run in order to set up their machines (according to the group they're working in)

2021-03-29 21:52 UTC, pgoodwin commented on scripts/opt-in/python.sh
> -
Just added a commit to take care of this.

2021-03-29 21:57 UTC, jtzero commented
lg;tm

2021-03-29 21:58 UTC, merged