Add setup for Awsume w/ SSO
rxrevu/workstation-setup pull request #51
Opened 2023-05-04 19:29 UTC by hantzje-arrive

[#182610955](https://www.pivotaltracker.com/story/show/182610955)

Adds awsume setup and the sso profile to the example ~/.aws/config

2023-05-04 22:28 UTC, pgoodwin commented on files/aws_config.example
> +region = us-east-1
Maybe stick this line at the top of the section like the others

2023-05-04 22:32 UTC, don-schram-rxrevu requested changes
I would also add `sso_account_name = rxrevu-security` to it.

2023-05-05 13:35 UTC, hantzje-arrive commented on files/aws_config.example
> +region = us-east-1
Done

2023-05-05 15:51 UTC, don-schram-rxrevu approved these changes

2023-05-05 17:54 UTC, anlewis approved these changes

2023-05-05 17:55 UTC, merged